Repository OurMenu/OurMenu-FE, pull requests merged in 2024-08, with the labels that each got.

#54 feat: http에서 https로 변경 완료
  app/build.gradle.kts
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/retrofit/NetworkModule.kt
  app/src/main/java/com/example/ourmenu/retrofit/RetrofitObject.kt
  app/src/main/res/raw/bluesparrow_shop.crt
Labels: ✨ feat, 🆗 merge

#56 Refactor/add menu page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/AddMenuSelectMenuFragment.kt
  app/src/main/java/com/example/ourmenu/account/LoginFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuActivity.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuMapFragment.kt
  app/src/main/res/layout/fragment_add_menu_map.xml
  app/src/main/res/layout/fragment_add_menu_select_menu.xml
Labels: ⚡️ fix, ♻️ refactor, 🆗 merge

#57 refactor : 코드리뷰 반영
  .idea/other.xml
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/adapter/PostMenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
Labels: ♻️ refactor, 🆗 merge

#58 fix : 캐러셀? 형태로 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuMainRVAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_menu_main.xml
Labels: ✨ feat, ⚡️ fix, 🆗 merge

#60 Feat/all menu
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailAllRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFilterFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
  app/src/main/res/drawable/btn_bg_12_n400.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_slider_thumb_left.xml
  app/src/main/res/drawable/ic_slider_thumb_right.xml
  app/src/main/res/layout/fragment_menu_folder.xml
  app/src/main/res/layout/fragment_menu_folder_detail_all.xml
  app/src/main/res/layout/fragment_menu_folder_detail_all_filter.xml
Labels: 💄 design, ✨ feat, 🆗 merge

#64 Refactor/overall2
  app/src/main/java/com/example/ourmenu/AddMenuSelectMenuFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuMapFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuPlaceMenuRVAdapter.kt
  app/src/main/java/com/example/ourmenu/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_add_menu_map.xml
  app/src/main/res/layout/fragment_add_menu_select_menu.xml
  app/src/main/res/layout/fragment_community_post.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_menu_folder.xml
  app/src/main/res/layout/fragment_menu_folder_detail.xml
  app/src/main/res/layout/fragment_post_menu_folder.xml
  app/src/main/res/layout/item_add_menu_btn.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/values/themes.xml
Labels: 🩹 chore, ♻️ refactor, 🆗 merge

#66 Refactor/overall
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderAllFilterSpinnerAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFilterFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/res/layout/community_filter_spinner_default.xml
  app/src/main/res/layout/community_filter_spinner_item.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_menu_folder_detail_all.xml
  app/src/main/res/layout/fragment_menu_folder_detail_all_filter.xml
  app/src/main/res/layout/item_menu_folder_detail_menu.xml
Labels: ✨ feat, ♻️ refactor, 🆗 merge

#68 Feat/api/menu
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/callback/DragItemTouchHelperCallback.kt
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostGetFragment.kt
  app/src/main/java/com/example/ourmenu/community/write/adapter/CommunityWritePostGetDetailRVAdapter.kt
  app/src/main/java/com/example/ourmenu/community/write/adapter/CommunityWritePostGetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/data/BaseResponse.kt
  app/src/main/java/com/example/ourmenu/data/MenuFolder.kt
  app/src/main/java/com/example/ourmenu/data/menu/data/MenuData.kt
  app/src/main/java/com/example/ourmenu/data/menu/response/MenuResponse.kt
  app/src/main/java/com/example/ourmenu/data/menuFolder/data/MenuFolderData.kt
  app/src/main/java/com/example/ourmenu/data/menuFolder/request/MenuFolderRequest.kt
  app/src/main/java/com/example/ourmenu/data/menuFolder/response/MenuFolderReponse.kt
  app/src/main/java/com/example/ourmenu/data/onboarding/data/OnboardingData.kt
  app/src/main/java/com/example/ourmenu/data/onboarding/response/OnboardingResponse.kt
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuMainRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderAllFilterSpinnerAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailAllRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailFilterSpinnerAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/callback/DiffUtilCallback.kt
  app/src/main/java/com/example/ourmenu/menu/callback/SwipeItemTouchHelperCallback.kt
  app/src/main/java/com/example/ourmenu/menu/iteminterface/MenuFolderItemClickListener.kt
  app/src/main/java/com/example/ourmenu/menu/iteminterface/MenuItemClickListener.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/adapter/PostMenuFolderGetDetailRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/adapter/PostMenuFolderGetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/adapter/PostMenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/adapter/MenuInfoVPAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/RetrofitObject.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuFolderService.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuService.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/OnboardingService.kt
  app/src/main/java/com/example/ourmenu/util/Utils.kt
  app/src/main/res/drawable/ic_dice_2.png
  app/src/main/res/drawable/ic_onboarding_chat.xml
  app/src/main/res/drawable/icon_28_thumbsdown.png
  app/src/main/res/drawable/icon_28_thumbsup.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_menu_folder.xml
  app/src/main/res/layout/fragment_menu_folder_detail.xml
  app/src/main/res/layout/fragment_menu_folder_detail_all.xml
  app/src/main/res/layout/fragment_post_menu_folder.xml
  app/src/main/res/layout/fragment_post_menu_folder_get.xml
  app/src/main/res/layout/home_onboarding_dialog.xml
  app/src/main/res/layout/item_add_menu_btn.xml
  app/src/main/res/layout/item_menu_folder.xml
  app/src/main/res/layout/item_menu_folder_detail_menu.xml
  app/src/main/res/layout/menu_folder_detail_spinner_default.xml
Labels: 💄 design, ✨ feat, ♻️ refactor, 🆗 merge

#69 Api/Email
  app/build.gradle.kts
  app/src/main/java/com/example/ourmenu/account/SignupEmailCertifyFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/data/account/AccountData.kt
  app/src/main/java/com/example/ourmenu/data/account/AccountResponse.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/AccountService.kt
Labels: 🚫 merge

#73 Api/add menu
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuMapFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuSelectMenuFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuTagFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuPlaceMenuRVAdapter.kt
  app/src/main/java/com/example/ourmenu/addMenu/bottomSheetClass/AddMenuBottmSheetIcon.kt
  app/src/main/java/com/example/ourmenu/data/menu/request/MenuRequest.kt
  app/src/main/java/com/example/ourmenu/data/menu/response/MenuResponse.kt
  app/src/main/java/com/example/ourmenu/data/menuFolder/data/MenuFolderData.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/RetrofitObject.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuService.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/PlaceService.kt
  app/src/main/res/drawable/dropdown_bg.xml
  app/src/main/res/layout/fragment_add_menu_map.xml
  app/src/main/res/layout/fragment_add_menu_name.xml
  app/src/main/res/layout/fragment_add_menu_select_menu.xml
  app/src/main/res/layout/item_add_menu_folder.xml
  app/src/main/res/layout/item_add_menu_name_menu_image.xml
  app/src/main/res/layout/item_add_menu_place_menu.xml
  app/src/main/res/layout/item_add_menu_search_result.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🆗 merge

#75 feat: naver map으로 이동 연결 완료
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoMapFragment.kt
Labels: ✨ feat, 🆗 merge

#72 feat : /onboarding GET
  app/build.gradle.kts
  app/src/main/java/com/example/ourmenu/data/onboarding/data/OnboardingData.kt
  app/src/main/java/com/example/ourmenu/data/onboarding/response/OnboardingResponse.kt
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/RetrofitObject.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/OnboardingService.kt
  app/src/main/java/com/example/ourmenu/util/Utils.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_onboarding_dialog.xml
Labels: ✨ feat, 🆗 merge

#78 Feat/api/home
  app/src/main/java/com/example/ourmenu/data/onboarding/response/OnboardingResponse.kt
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: ✨ feat, ⚡️ fix, 🆗 merge

#81 Feat/api/menu
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostGetFragment.kt
  app/src/main/java/com/example/ourmenu/data/menu/data/MenuData.kt
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuMainRVAdapter.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuSubRVAdapter.kt
  app/src/main/java/com/example/ourmenu/home/iteminterface/HomeItemClickListener.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/iteminterface/MenuFolderItemClickListener.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/adapter/PostMenuFolderGetDetailRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuService.kt
  app/src/main/res/layout/fragment_menu_folder_detail_all.xml
  app/src/main/res/layout/fragment_menu_info.xml
Labels: ✨ feat, 🆗 merge

#82 fix : hint, button, filter 높이 설정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetFragment.kt
  app/src/main/res/layout/fragment_menu_folder_detail_all.xml
  app/src/main/res/layout/fragment_post_menu_folder.xml
  app/src/main/res/layout/fragment_post_menu_folder_get.xml
Labels: ✨ feat, ⚡️ fix, 🆗 merge

#83 Fix/addMenuBS
  app/src/main/java/com/example/ourmenu/account/SignupNicknameFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/bottomSheetClass/AddMenuBottmSheetIcon.kt
  app/src/main/res/layout/fragment_add_menu_tag.xml
Labels: ⚡️ fix, 🆗 merge

#84 Api/menu info map
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/map/MapFragment.kt
  app/src/main/java/com/example/ourmenu/map/adapter/MapBottomSheetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoMapFragment.kt
  app/src/main/res/layout/fragment_menu_info_map.xml
Labels: ✨ feat, 🆗 merge

#85 fix : 지도보기 버튼, 메뉴폴더 이미지수정, menuinfo 이미지로딩, 더보기
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuActivity.kt
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostGetFragment.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/iteminterface/MenuFolderItemClickListener.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoActivity.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuService.kt
  app/src/main/res/drawable/ic_chevron_up.xml
  app/src/main/res/layout/fragment_menu_folder.xml
  app/src/main/res/layout/fragment_menu_info.xml
Labels: ✨ feat, ⚡️ fix, 🆗 merge

#87 Refactor/overall3
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuMapFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuSelectMenuFragment.kt
  app/src/main/java/com/example/ourmenu/map/adapter/MapBottomSheetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoMapFragment.kt
  app/src/main/res/drawable/default_image.png
  app/src/main/res/drawable/ic_circle_orange.xml
  app/src/main/res/drawable/ic_logo_orange.xml
  app/src/main/res/drawable/ic_logo_white.xml
  app/src/main/res/layout/activity_account.xml
  app/src/main/res/layout/activity_landing.xml
  app/src/main/res/layout/fragment_add_menu_map.xml
  app/src/main/res/layout/fragment_add_menu_select_menu.xml
  app/src/main/res/layout/fragment_menu_info_map.xml
  app/src/main/res/layout/item_map_menu_info.xml
Labels: ♻️ refactor, 🆗 merge

#86 fix : menufolder GET 리스폰스 변경에 따른 리팩적용
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/data/menuFolder/response/MenuFolderReponse.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
  app/src/main/res/layout/fragment_login.xml
Labels: ⚡️ fix, 🆗 merge

#89 feat : 두번 뒤로가기 클릭 설정
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/account/LoginFragment.kt
  app/src/main/java/com/example/ourmenu/landing/LandingActivity.kt
Labels: ✨ feat, 🆗 merge

#91 Feat/api/menu
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuTagFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/bottomSheetClass/AddMenuBottmSheetIcon.kt
  app/src/main/java/com/example/ourmenu/data/BaseResponse.kt
  app/src/main/java/com/example/ourmenu/data/menu/data/MenuData.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuService.kt
  app/src/main/res/layout/fragment_menu_info.xml
Labels: ✨ feat, 🆗 merge

#103 Refactor/overall5
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuTagFragment.kt
  app/src/main/java/com/example/ourmenu/map/adapter/MapBottomSheetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoMapFragment.kt
  app/src/main/res/drawable/default_image.png
  app/src/main/res/layout/add_menu_bottom_sheet_icon.xml
  app/src/main/res/layout/fragment_add_menu_tag.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_menu_info.xml
  app/src/main/res/layout/item_menu_folder_detail_menu.xml
Labels: ♻️ refactor, 🆗 merge

#104 feat : menu folder icon, 메뉴 가져오기 오류 수정
  .idea/other.xml
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostFragment.kt
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostGetFragment.kt
  app/src/main/java/com/example/ourmenu/community/write/adapter/CommunityWritePostGetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/community/write/adapter/CommunityWritePostRVAdapter.kt
  app/src/main/java/com/example/ourmenu/data/onboarding/response/OnboardingResponse.kt
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailAllRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderDetailRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailAllFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderDetailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/PostMenuFolderGetFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/post/adapter/PostMenuFolderRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/retrofit/service/MenuFolderService.kt
  app/src/main/java/com/example/ourmenu/util/FolderIconUtil.kt
  app/src/main/res/drawable/chip_bg_oval_n400.xml
  app/src/main/res/drawable/ic_folder_chip_anger.png
  app/src/main/res/drawable/ic_folder_chip_boong_u_bbang.png
  app/src/main/res/drawable/ic_folder_chip_cloudy.png
  app/src/main/res/drawable/ic_folder_chip_happy.png
  app/src/main/res/drawable/ic_folder_chip_rising_sun.png
  app/src/main/res/drawable/ic_folder_chip_sad.png
  app/src/main/res/drawable/ic_folder_chip_snowman.png
  app/src/main/res/drawable/ic_folder_chip_sun.png
  app/src/main/res/layout/bottom_sheet_post_menu_folder_chip_icon.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_post_menu_folder.xml
  app/src/main/res/layout/item_menu_info_image.xml
Labels: 💄 design, ✨ feat, ⚡️ fix, 🆗 merge

#107 Feat/community time
  app/src/main/java/com/example/ourmenu/community/CommunityPostFragment.kt
  app/src/main/java/com/example/ourmenu/community/adapter/CommunityPostRVAdapter.kt
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostGetFragment.kt
  app/src/main/java/com/example/ourmenu/mypage/adapter/MypageRVAdapter.kt
  app/src/main/res/layout/bottom_sheet_post_menu_folder_chip_icon.xml
  app/src/main/res/layout/item_post.xml
Labels: ✨ feat, ♻️ refactor, 🆗 merge

#109 Fix/menu2
  app/src/main/java/com/example/ourmenu/community/CommunityFragment.kt
  app/src/main/java/com/example/ourmenu/community/CommunityPostFragment.kt
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostFragment.kt
  app/src/main/java/com/example/ourmenu/community/write/CommunityWritePostGetFragment.kt
  app/src/main/java/com/example/ourmenu/mypage/MypageFragment.kt
Labels: ⚡️ fix, 🆗 merge

#113 Design/bottomsheet
  app/src/main/java/com/example/ourmenu/data/menu/data/MenuData.kt
  app/src/main/java/com/example/ourmenu/map/adapter/MapBottomSheetRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoMapFragment.kt
  app/src/main/java/com/example/ourmenu/util/Utils.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/layout/item_add_menu_place_menu.xml
Labels: ♻️ refactor, 🆗 merge

#114 Feat/menu folder delete modal
  app/src/main/java/com/example/ourmenu/data/menu/data/MenuData.kt
  app/src/main/java/com/example/ourmenu/menu/menuInfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/menu/menufolder/MenuFolderFragment.kt
Labels: ✨ feat, 🆗 merge
