Repository OurMenu/OurMenu-FE, pull requests merged in 2024-07, with the labels that each got.

#3 fix/color
  app/src/main/res/values/colors.xml
Labels: 💄 design, 🆗 merge

#4 design/chip 칩 추가(태그에 사용되는 2가지)
  app/src/main/res/drawable/button_bg_enabled.xml
  app/src/main/res/drawable/button_shape_onboard.xml
  app/src/main/res/drawable/chip_shape_tag_added.xml
  app/src/main/res/drawable/chip_shape_tag_basic.xml
  app/src/main/res/layout/button_big.xml
  app/src/main/res/layout/button_onboard.xml
  app/src/main/res/layout/chip_tag_added.xml
  app/src/main/res/layout/chip_tag_basic.xml
  app/src/main/res/values/colors.xml
Labels: 💄 design, 🆗 merge

#6 fix/font 폰트파일 수정 및 회원가입 프래그먼트 생성
  app/src/main/java/com/example/ourmenu/SignupEmailFragment.kt
  app/src/main/res/font/pretendard_bold.xml
  app/src/main/res/font/pretendard_regular.xml
  app/src/main/res/font/pretendard_semibold.xml
  app/src/main/res/layout/button_big.xml
  app/src/main/res/layout/button_onboard.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/values/strings.xml
Labels: 💄 design, ⚡️ fix, 🆗 merge

#9 fix: font 패키지 weight 수정, edittext fontFamily 수정
  app/src/main/res/font/pretendard_bold.xml
  app/src/main/res/font/pretendard_semibold.xml
  app/src/main/res/layout/edittext_email.xml
  app/src/main/res/layout/edittext_normal.xml
Labels: ⚡️ fix, 🆗 merge

#11 design: title bar 추가
  .idea/.name
  app/src/main/res/drawable/ic_logo_ourmenu.xml
  app/src/main/res/drawable/ic_title_add.xml
  app/src/main/res/layout/titlebar.xml
  app/src/main/res/values/strings.xml
Labels: 💄 design, 🆗 merge

#14 design: 랜딩, 로그인 페이지 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/LoginSignupFragment.kt
  app/src/main/java/com/example/ourmenu/account/AccountActivity.kt
  app/src/main/java/com/example/ourmenu/account/LoginFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailSertifyFragment.kt
  app/src/main/java/com/example/ourmenu/landing/LandingActivity.kt
  app/src/main/res/drawable/button_bg_enabled.xml
  app/src/main/res/drawable/button_bg_outlined.xml
  app/src/main/res/drawable/checkbox_bg.xml
  app/src/main/res/drawable/ic_checkbox_checked.xml
  app/src/main/res/drawable/ic_checkbox_default.xml
  app/src/main/res/drawable/ic_google.xml
  app/src/main/res/drawable/ic_insta.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/drawable/ic_social_line.xml
  app/src/main/res/layout/activity_account.xml
  app/src/main/res/layout/activity_landing.xml
  app/src/main/res/layout/fragment_landing.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup_email_sertify.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💄 design, ✨ feat, ♻️ refactor, 🆗 merge

#12 Design/home fragment
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/res/drawable/sample_menu_image.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_menu_main.xml
  app/src/main/res/layout/item_home_menu_sub.xml
  app/src/main/res/values/themes.xml
Labels: 💄 design, 🆗 merge

#13 feat: 메인 메뉴 리사이클러뷰 기능완성
  app/src/main/java/com/example/ourmenu/data/HomeMenuData.kt
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuMainRVAdapter.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuSubRVAdapter.kt
  app/src/main/res/drawable/ic_sample_recommend.xml
  app/src/main/res/layout/fragment_home.xml
Labels: ✨ feat, 🆗 merge

#16 refactor : theme, font refactoring 완료
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_menu_sub.xml
  app/src/main/res/values/themes.xml
Labels: ♻️ refactor, 🆗 merge

#17 Feat/navigation bar
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/community/CommunityFragment.kt
  app/src/main/java/com/example/ourmenu/map/MapFragment.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFragment.kt
  app/src/main/java/com/example/ourmenu/mypage/MypageFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottom_navigation.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat, 🆗 merge

#22 fix:chip
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailSertifyFragment.kt
  app/src/main/res/drawable/chip_shape_tag.xml
  app/src/main/res/drawable/chip_shape_tag_added.xml
  app/src/main/res/drawable/chip_shape_tag_basic.xml
  app/src/main/res/drawable/spinner_shape_default.xml
  app/src/main/res/layout/chip_tag.xml
  app/src/main/res/layout/chip_tag_added.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/fragment_signup_email_sertify.xml
  app/src/main/res/values/themes.xml
Labels: 💄 design, ⚡️ fix, 🆗 merge

#19 design/menu info
  app/build.gradle.kts
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/menu/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuInfoVPAdapter.kt
  app/src/main/res/drawable/button_bg_corner_20_no_storke_white.xml
  app/src/main/res/drawable/ic_chevron_down.xml
  app/src/main/res/drawable/ic_clock.xml
  app/src/main/res/drawable/ic_fill_map_menu_info.xml
  app/src/main/res/drawable/ic_goto_map.xml
  app/src/main/res/drawable/ic_pen.xml
  app/src/main/res/layout/fragment_menu_info.xml
  app/src/main/res/layout/item_menu_info_image.xml
Labels: 💄 design, ✨ feat, 🆗 merge

#23 refactor: login page
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/account/LoginFragment.kt
  app/src/main/res/layout/activity_landing.xml
  app/src/main/res/layout/fragment_login.xml
Labels: 💄 design, ♻️ refactor, 🆗 merge

#26 design: map page
  app/src/main/java/com/example/ourmenu/map/MapFragment.kt
  app/src/main/res/drawable/bottom_sheet_bg.xml
  app/src/main/res/drawable/button_shape_goto_map.xml
  app/src/main/res/drawable/folder_chip_bg.xml
  app/src/main/res/drawable/ic_bottomsheet_btn.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_sample_foler.png
  app/src/main/res/drawable/menu_sample.png
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/strings.xml
Labels: 💄 design, ✨ feat, 🆗 merge

#25 fix:커서 앞쪽으로 이동되는 문제 해결
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/spinner_item_background_edit.xml
Labels: ⚡️ fix, 🆗 merge

#28 Feat/signup
  app/src/main/java/com/example/ourmenu/account/AccountActivity.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailSertifyFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupNameFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupPwFragment.kt
  app/src/main/java/com/example/ourmenu/adapters/SpinnerAdapter.kt
  app/src/main/res/drawable/spinner_shape_default.xml
  app/src/main/res/drawable/spinner_shape_dropdown_background.xml
  app/src/main/res/drawable/spinner_shape_dropdown_item.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/fragment_signup_email_sertify.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_pw.xml
  app/src/main/res/layout/spinner_item_background.xml
  app/src/main/res/layout/spinner_item_background_edit.xml
Labels: ✨ feat, ⚡️ fix, 🆗 merge

#31 Design/menu 메뉴 화면 디자인 완성
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFragment.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/callback/ItemTouchHelperCallback.kt
  app/src/main/res/drawable/button_bg_add_menu_neutral_100.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_my_menu.xml
  app/src/main/res/drawable/spinner_shape_default.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/item_menu_folder.xml
  app/src/main/res/layout/item_menu_info_image.xml
  app/src/main/res/values/themes.xml
Labels: 💄 design, ✨ feat, 🆗 merge

#29 Refactor/home menuinfo
  app/src/main/java/com/example/ourmenu/menu/MenuInfoFragment.kt
  app/src/main/res/drawable/button_shape_goto_map_orange.xml
  app/src/main/res/drawable/button_shape_goto_map_white.xml
  app/src/main/res/drawable/ic_map_orange.xml
  app/src/main/res/drawable/ic_map_white.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_menu_info.xml
Labels: 💄 design, ♻️ refactor, 🆗 merge

#32 Feat/signup email
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailSertifyFragment.kt
  app/src/main/java/com/example/ourmenu/account/adapters/SpinnerAdapter.kt
  app/src/main/res/drawable/ic_mappin_background_circle.xml
  app/src/main/res/drawable/ic_watermelon.xml
  app/src/main/res/drawable/spinner_shape_default.xml
  app/src/main/res/layout/fragment_menu_add_name.xml
  app/src/main/res/layout/fragment_menu_add_tag.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/fragment_signup_email_sertify.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_pw.xml
  app/src/main/res/layout/spinner_item_background_edit.xml
Labels: 💄 design, ✨ feat, 🆗 merge

#33 Design/menu folder
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menuinfo/MenuInfoActivity.kt
  app/src/main/java/com/example/ourmenu/menuinfo/MenuInfoFragment.kt
  app/src/main/res/drawable/ic_goto_button.xml
  app/src/main/res/layout/activity_menu_info.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_menu_folder.xml
  app/src/main/res/layout/fragment_menu_info.xml
  app/src/main/res/layout/item_menu_folder_detail_menu.xml
  app/src/main/res/layout/item_menu_info_image.xml
Labels: 💄 design, ✨ feat, ♻️ refactor, 🆗 merge

#35 feat : Home Fragment 아이템 클릭시 화면이동 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/home/HomeFragment.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuMainRVAdapter.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuSubRVAdapter.kt
  app/src/main/java/com/example/ourmenu/home/iteminterface/HomeItemClickListener.kt
  app/src/main/res/layout/activity_menu_info.xml
Labels: ✨ feat, ♻️ refactor, 🆗 merge

#38 Feat/menu folder
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFolderActivity.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuFolderRVAdapter.kt
  app/src/main/res/drawable/button_bg_bottom_corner_default.xml
  app/src/main/res/drawable/button_bg_bottom_corner_pressed.xml
  app/src/main/res/drawable/button_bg_cancel_default.xml
  app/src/main/res/drawable/button_bg_cancel_pressed.xml
  app/src/main/res/drawable/button_bg_ok.xml
  app/src/main/res/drawable/button_bg_top_corner_default.xml
  app/src/main/res/drawable/button_bg_top_corner_pressed.xml
  app/src/main/res/drawable/button_shape_bottom_corner.xml
  app/src/main/res/drawable/button_shape_cancel.xml
  app/src/main/res/drawable/button_shape_top_corner.xml
  app/src/main/res/drawable/cursor_edittext.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_vert.xml
  app/src/main/res/layout/activity_menu_folder.xml
  app/src/main/res/layout/fragment_menu_folder.xml
Labels: 💄 design, ✨ feat, ♻️ refactor, 🆗 merge

#39 Design/addmenuname
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/AddMenuTagFragment.kt
  app/src/main/java/com/example/ourmenu/MenuAddNameFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupEmailSertifyFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupPwFragment.kt
  app/src/main/java/com/example/ourmenu/data/AddMenuImageData.kt
  app/src/main/res/drawable/checkbox_bg.xml
  app/src/main/res/drawable/ic_checkbox_checked.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_union.xml
  app/src/main/res/drawable/spinner_shape_dropdown_item.xml
  app/src/main/res/layout/add_menu_name_menu_image_default.xml
  app/src/main/res/layout/fragment_add_menu_name.xml
  app/src/main/res/layout/fragment_add_menu_tag.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_menu_add_name.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/fragment_signup_email_sertify.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_pw.xml
  app/src/main/res/layout/spinner_default_background.xml
  app/src/main/res/values/attrs.xml
Labels: 💄 design, ♻️ refactor, 🆗 merge

#37 feat : 화면 이동 기능 추가
  app/src/main/java/com/example/ourmenu/menuinfo/MenuInfoFragment.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/fragment_menu_info.xml
  app/src/main/res/layout/item_menu_info_image.xml
Labels: ✨ feat, 🚫 merge

#41 Refactor/menu, menu-info, menu-folder, home
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ourmenu/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/home/adapter/HomeMenuMainRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFolderActivity.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFolderFragment.kt
  app/src/main/java/com/example/ourmenu/menu/MenuFragment.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/callback/ItemTouchHelperCallback.kt
  app/src/main/java/com/example/ourmenu/menu/iteminterface/MenuItemClickListener.kt
  app/src/main/res/drawable/button_bg_8dp_white.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_menu_folder.xml
  app/src/main/res/layout/item_menu_info_image.xml
Labels: 💄 design, ✨ feat, ♻️ refactor, 🆗 merge

#43 refactor: menu info map page
  app/src/main/java/com/example/ourmenu/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/MainActivity.kt
  app/src/main/java/com/example/ourmenu/map/MapFragment.kt
  app/src/main/java/com/example/ourmenu/menuinfo/MenuInfoFragment.kt
  app/src/main/java/com/example/ourmenu/menuinfo/MenuInfoMapFragment.kt
  app/src/main/res/layout/fragment_add_menu_map.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_menu_info.xml
  app/src/main/res/layout/fragment_menu_info_map.xml
Labels: 💄 design, ✨ feat, ♻️ refactor, 🆗 merge

#44 feat: map api
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuMapFragment.kt
  app/src/main/res/layout/fragment_add_menu_map.xml
  app/src/main/res/layout/fragment_menu_info_map.xml
  build.gradle.kts
  settings.gradle.kts
Labels: ✨ feat, ⚡️ fix, 🆗 merge

#42 Refactor/add menu
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/account/LoginFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupNameFragment.kt
  app/src/main/java/com/example/ourmenu/account/SignupPwFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuActivity.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuMapFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuTagFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/data/AddMenuImageData.kt
  app/src/main/res/drawable/ic_camera_enhance.xml
  app/src/main/res/drawable/icon_x.xml
  app/src/main/res/layout/add_menu_name_menu_image_default.xml
  app/src/main/res/layout/fragment_add_menu_name.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/item_add_menu_name_menu_image.xml
  gradle/libs.versions.toml
Labels: ♻️ refactor, 🆗 merge

#49 feat : 드래그앤 드롭 기능 완성
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuNameFragment.kt
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/addMenu/callback/DragItemTouchHelperCallback.kt
  app/src/main/java/com/example/ourmenu/menu/adapter/MenuRVAdapter.kt
  app/src/main/java/com/example/ourmenu/menu/callback/SwipeItemTouchHelperCallback.kt
  app/src/main/java/com/example/ourmenu/menu/menuFolder/MenuFolderFragment.kt
Labels: ✨ feat, 🆗 merge

#51 Fix/add menu layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ourmenu/addMenu/AddMenuActivity.kt
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/addMenu/callback/DragItemTouchHelperCallback.kt
Labels: ⚡️ fix, 🆗 merge

#50 feat/addMenuItemDrag
  app/src/main/java/com/example/ourmenu/addMenu/adapter/AddMenuImageAdapter.kt
  app/src/main/java/com/example/ourmenu/addMenu/callback/DragItemTouchHelperCallback.kt
Labels: ✨ feat, 🆗 merge
